# Generated by Django 4.1.13 on 2024-02-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
