# Generated by Django 4.1.13 on 2024-03-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
